name: "Terraform plan"

on:
  workflow_dispatch:
#  push:
#     branches:
#            - main

jobs:
   terraform:
         name: "Terraform"
         runs-on: "ubuntu-latest"

         steps:
           - name: Checkout
             uses: actions/checkout@v2


           - name: setup terraform
             uses: hashicorp/setup-terraform@v1
             with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

           - name: copy files
	     run: cp * terraform_temp/
			 	 
           - name: Terraform Init
	     working-directory: ./terraform_temp
             id: init
             run: terraform init

           - name: Terraform plan
	     working-directory: ./terraform_temp
             id: plan
 #            if: github.event_name == 'push'
             run: terraform plan     

           - name: Terraform apply
	     working-directory: ./terraform_temp
             id: apply
    #         if: github.event_name == 'push'
             run: terraform apply -auto-approve      

