name: "Terraform plan"

on:
  workflow_dispatch:
#  push:
#     branches:
#            - main

jobs:
   terraform:
         name: "Terraform"
         runs-on: "ubuntu-latest"

         steps:
           - name: Checkout
             uses: actions/checkout@v2
	   - name: Clone terraform code
             run : git clone https://github.com/jitenderyadavofc/test-repo.git terraform
	     
